### ISSUE TITLE
Category Template

### ISSUE THREAD

**Issue by eduardolinkspot** [varunsridharan/woocommerce-attributes-menu-manager#5]
Hello, after installing your plugin I cannot configure the taxonomy-pa_slug.php to work correctly, I have followed the instructions and make a copy of my taxonomy-product_cat.php and renamed it in my theme folder/woocomece/ 

The file is exactly the same with just a different name, but my categories page configurations were not applied to the attributes page.

You can see it here: 

Categories page: http://canaldopiso.com.br/site2016/categoria-produto/conservacao-ceras/

Attributes page: http://canaldopiso.com.br/site2016/pa_marca/bellinzoni/

As you can see, there are some information i don´t want to show in the products, like categories, sku and long description, theses options are available to show or hide in my theme options, but in the attribute page theses options were not loaded and the final result is all these fields appearing in the attribute page.

I really appreciate if you can help me to solve this issue.

Thank you very much

**Comment by varunsridharan** [comment]
@eduardolinkspot
I Replied in [WP.ORG](https://wordpress.org/support/topic/category-template-15?replies=2#post-7949078)
